### ISSUE TITLE
resource/symptom.txt not found 

### ISSUE THREAD

**Issue by riverind** [MissuQAQ/Medical_KG#1]
to run python main.py

设置随机数种子为70
os.path.join(config.store_path is Medical_KG/resource
Traceback (most recent call last):
  File "Medical_KG/main.py", line 17, in <module>
    handler = QuestionClassifier(config)
  File "Medical_KG/question_classifier.py", line 20, in __init__
    self.symptoms_lists = [i.strip() for i in open(os.path.join(config.store_path,'symptom.txt')) if i.strip()]
FileNotFoundError: [Errno 2] No such file or directory: 'Medical_KG/resource/symptom.txt'

thx

**Comment by yyimingucl** [comment]
Hi, 

thanks for opening the issue. The project had been done long time ago. I can't be sure. You can try unzip the two .rar files in 'Medical_KG/resource' resource folder. Then run the main file. 

Hope it works : ).

Best.
